export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/s1.webp",
      description: "very nice clothe",
      price: 649,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Narrow Blue fit Jeans",
      category: "Pants",
      image: "/images/s1.webp",
      description: "very nice clothe",
      price: 1669,
      brand: "Diesel",
      rating: 4.3,
      numReviews: 15,
      countInStock: 12,
    },
    {
      _id: "3",
      name: "Navy Blue dotted Slim Shirt",
      category: "Shirts",
      image: "/images/s1.webp",
      description: "very nice clothe",
      price: 999,
      brand: "Nike",
      rating: 4.2,
      numReviews: 5,
      countInStock: 4,
    },
    {
      _id: "4",
      name: "Regular Fit Teal Shirt",
      category: "Shirts",
      image: "/images/s1.webp",
      description: "very nice clothe",
      price: 1099,
      brand: "Nike",
      rating: 4.2,
      numReviews: 11,
      countInStock: 5,
    },
  ],
};
